export const CATEGORIAS = [
  { id: 'todas', nombre: 'Todas las categorías' },
  { id: 'ofertas', nombre: 'Ofertas' },
  { id: 'abarrotes', nombre: 'Abarrotes' },
  { id: 'frutas', nombre: 'Frutas y verduras' },
  { id: 'lacteos', nombre: 'Lácteos' },
  { id: 'limpieza', nombre: 'Limpieza' },
];

export const ENVIO_GRATIS_DESDE = 150;
export const COSTO_ENVIO = 8;

export const PRODUCTOS = [
  { id: 1,  nombre: 'Arroz superior',     presentacion: 'Bolsa 5 kg',   categoria: 'abarrotes', precio: 18.5, antes: 21.9, img: 'img/productos/arroz-superior.svg' },
  { id: 2,  nombre: 'Aceite vegetal',     presentacion: 'Botella 1 L',  categoria: 'abarrotes', precio: 7.9,  antes: 9.5,  img: 'img/productos/aceite-vegetal.svg' },
  { id: 3,  nombre: 'Fideos spaghetti',   presentacion: 'Bolsa 500 g',  categoria: 'abarrotes', precio: 3.2,  antes: null, img: 'img/productos/fideos-spaghetti.svg' },
  { id: 4,  nombre: 'Azúcar rubia',       presentacion: 'Bolsa 1 kg',   categoria: 'abarrotes', precio: 4.1,  antes: null, img: 'img/productos/azucar-rubia.svg' },
  { id: 5,  nombre: 'Leche evaporada',    presentacion: 'Lata 400 g',   categoria: 'lacteos',   precio: 3.8,  antes: null, img: 'img/productos/leche-evaporada.svg' },
  { id: 6,  nombre: 'Manzana Delicia',    presentacion: 'Malla 1 kg',   categoria: 'frutas',    precio: 4.5,  antes: null, img: 'img/productos/manzana-delicia.svg' },
  { id: 7,  nombre: 'Plátano de seda',    presentacion: 'Kilo',         categoria: 'frutas',    precio: 3.0,  antes: 3.8,  img: 'img/productos/platano-de-seda.svg' },
  { id: 8,  nombre: 'Naranja de jugo',    presentacion: 'Malla 1 kg',   categoria: 'frutas',    precio: 2.8,  antes: null, img: 'img/productos/naranja-de-jugo.svg' },
  { id: 9,  nombre: 'Mandarina',          presentacion: 'Kilo',         categoria: 'frutas',    precio: 3.5,  antes: 4.5,  img: 'img/productos/mandarina.svg' },
  { id: 10, nombre: 'Detergente',         presentacion: 'Bolsa 2 kg',   categoria: 'limpieza',  precio: 14.9, antes: 18.9, img: 'img/productos/detergente.svg' },
  { id: 11, nombre: 'Lavavajilla',        presentacion: 'Crema 500 g',  categoria: 'limpieza',  precio: 6.9,  antes: null, img: 'img/productos/lavavajilla.svg' },
  { id: 12, nombre: 'Lejía',              presentacion: 'Botella 1 L',  categoria: 'limpieza',  precio: 5.5,  antes: null, img: 'img/productos/lejia.svg' },
  { id: 13, nombre: 'Queso fresco',       presentacion: 'Paquete 250 g',categoria: 'lacteos',   precio: 9.9,  antes: null, img: 'img/productos/queso-fresco.svg' },
  { id: 14, nombre: 'Yogurt natural',     presentacion: 'Botella 1 L',  categoria: 'lacteos',   precio: 7.5,  antes: 8.9,  img: 'img/productos/yogurt-natural.svg' },
  { id: 15, nombre: 'Atún en aceite',     presentacion: 'Lata 170 g',   categoria: 'abarrotes', precio: 5.2,  antes: 6.5,  img: 'img/productos/atun-en-aceite.svg' },
  { id: 16, nombre: 'Leche entera UHT Gloria', presentacion: 'Caja 946 ml', categoria: 'lacteos', precio: 6.5, antes: null, img: 'img/productos/leche-entera-uht-gloria.svg' },
  { id: 17, nombre: 'Leche UHT Laive', presentacion: 'Bolsa 800 ml', categoria: 'lacteos', precio: 4.8, antes: null, img: 'img/productos/leche-uht-laive.svg' },
  { id: 18, nombre: 'Leche evaporada Bella Holandesa', presentacion: 'Lata 405 g', categoria: 'lacteos', precio: 3.4, antes: null, img: 'img/productos/leche-evaporada-bella-holandesa.svg' },
  { id: 19, nombre: 'Leche pasteurizada Danlac', presentacion: 'Botella 900 ml', categoria: 'lacteos', precio: 8.1, antes: null, img: 'img/productos/leche-pasteurizada-danlac.svg' },
  { id: 20, nombre: 'Leche UHT Vigor', presentacion: 'Bolsa 800 ml', categoria: 'lacteos', precio: 5.3, antes: null, img: 'img/productos/leche-uht-vigor.svg' },
  { id: 21, nombre: 'Leche UHT Milkito', presentacion: 'Bolsa 800 ml', categoria: 'lacteos', precio: 4.8, antes: null, img: 'img/productos/leche-uht-milkito.svg' },
  { id: 22, nombre: 'Leche sabor chocolate Gloria', presentacion: 'Caja 946 ml', categoria: 'lacteos', precio: 7.2, antes: null, img: 'img/productos/leche-sabor-chocolate-gloria.svg' },
  { id: 23, nombre: 'Pack x6 leche evaporada Gloria', presentacion: 'Entera', categoria: 'lacteos', precio: 24.9, antes: null, img: 'img/productos/pack-x6-leche-evaporada-gloria.svg' },
  { id: 24, nombre: 'Sixpack leche reconstituida Gloria', presentacion: 'Lata 390 g', categoria: 'lacteos', precio: 21.8, antes: null, img: 'img/productos/sixpack-leche-reconstituida-gloria.svg' },
  { id: 25, nombre: 'Leche ultrafiltrada sin lactosa Gloria Zero Lacto', presentacion: 'Lata 390 g', categoria: 'lacteos', precio: 4.5, antes: null, img: 'img/productos/leche-ultrafiltrada-sin-lactosa-gloria-zero-lacto.svg' },
  { id: 26, nombre: 'Leche light Laive sin lactosa', presentacion: 'Botella 390 g', categoria: 'lacteos', precio: 4.9, antes: null, img: 'img/productos/leche-light-laive-sin-lactosa.svg' },
  { id: 27, nombre: 'Leche reconstituida Gloria', presentacion: 'Lata 390 g', categoria: 'lacteos', precio: 4.5, antes: null, img: 'img/productos/leche-reconstituida-gloria.svg' },
  { id: 28, nombre: 'Leche reconstituida Gloria Light', presentacion: 'Lata 390 g', categoria: 'lacteos', precio: 4.5, antes: null, img: 'img/productos/leche-reconstituida-gloria-light.svg' },
  { id: 29, nombre: 'Leche concentrada sin lactosa Laive', presentacion: 'Botella 390 g', categoria: 'lacteos', precio: 4.9, antes: null, img: 'img/productos/leche-concentrada-sin-lactosa-laive.svg' },
  { id: 30, nombre: 'Leche para diluir Laive', presentacion: 'Botella 390 g', categoria: 'lacteos', precio: 4.7, antes: null, img: 'img/productos/leche-para-diluir-laive.svg' },
  { id: 31, nombre: 'Leche evaporada light Cuisine & Co', presentacion: 'Lata 410 g', categoria: 'lacteos', precio: 4.2, antes: null, img: 'img/productos/leche-evaporada-light-cuisine-co.svg' },
  { id: 32, nombre: 'Leche UHT Gloria Light', presentacion: 'Caja 946 ml', categoria: 'lacteos', precio: 6.5, antes: null, img: 'img/productos/leche-uht-gloria-light.svg' },
  { id: 33, nombre: 'Leche UHT sin lactosa Gloria Zero Lacto', presentacion: 'Caja 946 ml', categoria: 'lacteos', precio: 6.5, antes: null, img: 'img/productos/leche-uht-sin-lactosa-gloria-zero-lacto.svg' },
  { id: 34, nombre: 'Leche entera UHT Laive', presentacion: 'Caja 946 ml', categoria: 'lacteos', precio: 5.9, antes: null, img: 'img/productos/leche-entera-uht-laive.svg' },
  { id: 35, nombre: 'Leche descremada UHT Laive Sbelt', presentacion: 'Caja 946 ml', categoria: 'lacteos', precio: 5.9, antes: null, img: 'img/productos/leche-descremada-uht-laive-sbelt.svg' },
  { id: 36, nombre: 'Leche semidescremada UHT Laive sin lactosa', presentacion: 'Caja 946 ml', categoria: 'lacteos', precio: 5.9, antes: null, img: 'img/productos/leche-semidescremada-uht-laive-sin-lactosa.svg' },
  { id: 37, nombre: 'Leche entera UHT Gloria', presentacion: 'Bolsa 800 ml', categoria: 'lacteos', precio: 4.9, antes: null, img: 'img/productos/leche-entera-uht-gloria.svg' },
  { id: 38, nombre: 'Leche parcialmente descremada Gloria Light', presentacion: 'Bolsa 800 ml', categoria: 'lacteos', precio: 4.7, antes: null, img: 'img/productos/leche-parcialmente-descremada-gloria-light.svg' },
  { id: 39, nombre: 'Leche UHT sin lactosa Vigor', presentacion: 'Bolsa 800 ml', categoria: 'lacteos', precio: 5.5, antes: null, img: 'img/productos/leche-uht-sin-lactosa-vigor.svg' },
  { id: 40, nombre: 'Leche deslactosada Danlac Light', presentacion: 'Botella 900 ml', categoria: 'lacteos', precio: 9.0, antes: null, img: 'img/productos/leche-deslactosada-danlac-light.svg' },
  { id: 41, nombre: 'Leche UHT entera Cuisine & Co', presentacion: 'Caja 1 L', categoria: 'lacteos', precio: 5.9, antes: null, img: 'img/productos/leche-uht-entera-cuisine-co.svg' },
  { id: 42, nombre: 'Leche en polvo Gloria', presentacion: 'Bolsa 96 g', categoria: 'lacteos', precio: 5.7, antes: null, img: 'img/productos/leche-en-polvo-gloria.svg' },
  { id: 43, nombre: 'Bebida láctea sabor chocolate Bonlé', presentacion: 'Bolsa 800 ml', categoria: 'lacteos', precio: 3.6, antes: null, img: 'img/productos/bebida-lactea-sabor-chocolate-bonle.svg' },
  { id: 44, nombre: 'Leche chocolatada Gloria', presentacion: 'Bolsa 900 ml', categoria: 'lacteos', precio: 6.4, antes: null, img: 'img/productos/leche-chocolatada-gloria.svg' },
  { id: 45, nombre: 'Tripack leche entera UHT Gloria', presentacion: 'Caja 946 ml', categoria: 'lacteos', precio: 16.2, antes: 18.0, img: 'img/productos/tripack-leche-entera-uht-gloria.svg' },
  { id: 46, nombre: 'Tripack leche UHT Gloria Light', presentacion: 'Caja 946 ml', categoria: 'lacteos', precio: 16.5, antes: null, img: 'img/productos/tripack-leche-uht-gloria-light.svg' },
  { id: 47, nombre: 'Fourpack leche entera UHT Laive', presentacion: 'Caja 946 ml', categoria: 'lacteos', precio: 20.9, antes: null, img: 'img/productos/fourpack-leche-entera-uht-laive.svg' },
  { id: 48, nombre: 'Sixpack leche Gloria Niños', presentacion: 'Lata 390 g', categoria: 'lacteos', precio: 22.9, antes: null, img: 'img/productos/sixpack-leche-gloria-ninos.svg' },
  { id: 49, nombre: 'Sixpack leche light Laive sin lactosa', presentacion: 'Botella 390 g', categoria: 'lacteos', precio: 21.9, antes: 25.9, img: 'img/productos/sixpack-leche-light-laive-sin-lactosa.svg' },
  { id: 50, nombre: 'Pack x6 leche reconstituida entera Gloria', presentacion: 'Lata 390 g', categoria: 'lacteos', precio: 22.9, antes: 24.6, img: 'img/productos/pack-x6-leche-reconstituida-entera-gloria.svg' },
  { id: 51, nombre: 'Pack x6 mezcla láctea Laive sin lactosa', presentacion: '480 g', categoria: 'lacteos', precio: 23.4, antes: null, img: 'img/productos/pack-x6-mezcla-lactea-laive-sin-lactosa.svg' },
  { id: 52, nombre: 'Sixpack mezcla láctea Bonlé Familiar', presentacion: 'Caja 480 g', categoria: 'lacteos', precio: 19.7, antes: null, img: 'img/productos/sixpack-mezcla-lactea-bonle-familiar.svg' },
];

export const buscarProducto = (id) => PRODUCTOS.find((p) => p.id === id);
